#!/bin/bash

set -e
cd $(dirname $0)/..

npm_bin=$(npm bin)

echo "Linting src"
npm run lint

echo "Cleaning build"
rm -rf build
mkdir build

echo "Compiling with TypeScript"
$npm_bin/tsc -d

echo "Compiling .flow.js definition files"
npm run build-dot-flow
